site_name: Mine Life Wiki
pages:
  - Home: index.md
  - Deutsch:
      - Areas: Deutsch/areas.md
      - Bahnlinien: Deutsch/bahnlinien.md
      - Befehle auf einen Blick: Deutsch/befehleAufEinenBlick.md
      - Inaktivitaet: Deutsch/inaktivitaet.md
      - Jobs: Deutsch/jobs.md
      - Lizenzen: Deutsch/licenses.md
      - Regeln: Deutsch/Rules.md
      - Staedte: Deutsch/stadt.md
      - Vertraege: Deutsch/vertraege.md
      - Wie kann ich Starten?: Deutsch/HowToStart.md
      - Wirtschaft: Deutsch/wirtschaft.md
      - Zonen: Deutsch/gebiete.md

  - English:
      - Areas: English/areas.md
      - Cities: English/stadt.md
      - Contracts: English/vertraege.md
      - Commands at a glance: English/befehleAufEinenBlick.md
      - Economy: English/wirtschaft.md
      - How to start?: English/HowToStart.md
      - Inactivity: English/inaktiviaet.md
      - Jobs: English/jobs.md
      - Licenses: English/licenses.md
      - Railway lines: English/bahnlinien.md
      - Rules: English/Rules.md
      - Zones: English/gebiete.md

theme: readthedocs
